version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=investit
      - MYSQL_ROOT_PASSWORD=admin0000
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin0000
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./investit.sql:/docker-entrypoint-initdb.d/investit.sql
volumes:
  db:
    driver: local
